### ISSUE TITLE
from_PyCMDS breaks for 1D and TuneTest data. 

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#432]
Currently working in synced with origin `'3.0.0-development'`. I have encountered two instances when `data.from_PyCMDS` breaks. 

The first instance is when I call `wt.data.from_PyCMDS` on [this](https://drive.google.com/open?id=0BzJTClorMBuwb3dVMnhwZGx6REU) file I get the following error. `TypeError: unhashable type: 'slice'` on [this](https://github.com/wright-group/WrightTools/blob/development/WrightTools/data/_pycmds.py#L146) line of code: ` meshgrid = tuple([axes[0][:]])`.

I haven't understood the core problem. But I will note:
- Given that `meshgrid` is only used inside of the `if any(interpolate_toggles):`  it should probably be put inside of that `if` block and not called before it. 

The second instance is when importing [this](https://drive.google.com/open?id=0BzJTClorMBuwUllvaG5Iek9OX1U) TuneTest file which has array data. I get the following error `AttributeError: 'dict' object has no attribute 'name'` on [this](https://github.com/wright-group/WrightTools/blob/development/WrightTools/data/_pycmds.py#L121) line of code: `centers = np.array(headers[axis.name + ' centers'])`

**Comment by ksunden** [comment]
`axis.name` should probably be `axis.expression`

That was one of the things that was changed with the transition to variables. `name` is an attribute of variables, not axes. However, I believe we want the full expression here. for all PyCMDS generated data files, this should be identical, as there should only be one variable in this axis, I believe.

**Comment by ksunden** [comment]
I agree that meshgrid can be moved, though I'm unclear as to why it failed, and it still may fail for 1-D data where it is desired
